[package]
name = "distributed-tracing-ui"
version = "0.1.0"
authors = ["Ryan Christian <christianr@cardiff.ac.uk"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
yew = "0.12"
wasm-bindgen = "0.2.58"
serde = "1.0.104"
serde_derive = "1.0.104"
strum = "0.17.1"
strum_macros = "0.17.1"
log = "0.4.8"
web_logger = "0.2.0"


# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.4", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"
